controller_list:
  - name: fake_a3c_plan_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_solver_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses per group
  - group: a3c_plan_group
    pose: home_pose