controller_list:
  - name: joint_traj_controller_moveit
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: gripper_moveit
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - finger_joint
